<a href="https://colab.research.google.com/github/Tanishq-Btech/ML-assignments/blob/main/Self_Learning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/loan_data_set.csv')

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df=df.drop(columns=['Loan_ID'])

In [5]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [7]:
from sklearn.preprocessing import OneHotEncoder        # import OneHotEncoder from sklearn
oe=OneHotEncoder()

In [11]:
df['Gender']=oe.fit_transform(df[['Gender']]).toarray()        # Use of onehotencoder for nominal data
df['Married']=oe.fit_transform(df[['Married']]).toarray()
df['Education']=oe.fit_transform(df[['Education']]).toarray()
df['Self_Employed']=oe.fit_transform(df[['Self_Employed']]).toarray()
df['Property_Area']=oe.fit_transform(df[['Property_Area']]).toarray()
df['Loan_Status']=oe.fit_transform(df[['Loan_Status']]).toarray()

In [12]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1.0,1.0,0,1.0,1.0,5849,0.0,NaN,360.0,1.0,0.0,0.0
1,1.0,0.0,1,1.0,1.0,4583,1508.0,128.0,360.0,1.0,1.0,1.0
2,1.0,0.0,0,1.0,0.0,3000,0.0,66.0,360.0,1.0,0.0,0.0
3,1.0,0.0,0,0.0,1.0,2583,2358.0,120.0,360.0,1.0,0.0,0.0
4,1.0,1.0,0,1.0,1.0,6000,0.0,141.0,360.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,1.0,0,1.0,1.0,2900,0.0,71.0,360.0,1.0,1.0,0.0
610,1.0,0.0,3+,1.0,1.0,4106,0.0,40.0,180.0,1.0,1.0,0.0
611,1.0,0.0,1,1.0,1.0,8072,240.0,253.0,360.0,1.0,0.0,0.0
612,1.0,0.0,2,1.0,1.0,7583,0.0,187.0,360.0,1.0,0.0,0.0
613,0.0,1.0,0,1.0,0.0,4583,0.0,133.0,360.0,0.0,0.0,1.0

In [18]:
from sklearn.impute import  SimpleImputer                       # Use of SimpleImputer Library for filling missing values
se=SimpleImputer(missing_values=np.nan,strategy='mean')
df['Dependents'] = df['Dependents'].replace('3+', '3')
df['Dependents'] = pd.to_numeric(df['Dependents'])
se.fit(df[['Married', 'Dependents']])
df[['Married', 'Dependents']]=se.transform(df[['Married', 'Dependents']])

In [21]:
df[['LoanAmount','Loan_Amount_Term','Credit_History']]=se.fit_transform(df[['LoanAmount','Loan_Amount_Term','Credit_History']])

In [22]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1.0,1.0,0.0,1.0,1.0,5849,0.0,146.412162,360.0,1.0,0.0,0.0
1,1.0,0.0,1.0,1.0,1.0,4583,1508.0,128.000000,360.0,1.0,1.0,1.0
2,1.0,0.0,0.0,1.0,0.0,3000,0.0,66.000000,360.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,2583,2358.0,120.000000,360.0,1.0,0.0,0.0
4,1.0,1.0,0.0,1.0,1.0,6000,0.0,141.000000,360.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,1.0,0.0,1.0,1.0,2900,0.0,71.000000,360.0,1.0,1.0,0.0
610,1.0,0.0,3.0,1.0,1.0,4106,0.0,40.000000,180.0,1.0,1.0,0.0
611,1.0,0.0,1.0,1.0,1.0,8072,240.0,253.000000,360.0,1.0,0.0,0.0
612,1.0,0.0,2.0,1.0,1.0,7583,0.0,187.000000,360.0,1.0,0.0,0.0
613,0.0,1.0,0.0,1.0,0.0,4583,0.0,133.000000,360.0,0.0,0.0,1.0

In [23]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64